// showReducer
export const FETCH_SHOWS_INFO_START = 'FETCH_SHOWS_INFO_START';
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS';
export const FETCH_SHOWS_INFO_FAILED = 'FETCH_SHOWS_INFO_FAILED';
export const SORT_SHOWS = 'SORT_SHOWS';

// Posters
export const FETCH_POSTER_SUCCESS = 'FETCH_POSTERS_SUCCESS';

// Pagination
export const GET_AMOUNT_OF_PAGES = 'GET_AMOUNT_OF_PAGES';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

// sortReducer
export const SET_SORTING_ORDER = 'SET_SORTING_ORDER';

// searchReducer
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SEARCH_SHOWS_START = 'SEARCH_SHOWS_START';
export const SEARCH_SHOWS_FAILED = 'SEARCH_SHOWS_FAILED';
export const SEARCH_SHOWS_SUCCESS = 'SEARCH_SHOWS_SUCCESS';

// errorReducer
export const GET_ERRORS = 'GET_ERRORS';