// showReducer
export const FETCH_SHOWS_INFO_START = 'FETCH_SHOWS_INFO_START';
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS';
export const FETCH_SHOWS_INFO_FAILED = 'FETCH_SHOWS_INFO_FAILED';
// Posters
export const FETCH_POSTER_SUCCESS = 'FETCH_POSTERS_SUCCESS';

// Pagination
export const GET_AMOUNT_OF_PAGES = 'GET_AMOUNT_OF_PAGES';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

// errorReducer
export const GET_ERRORS = 'GET_ERRORS';